[package]
name = "near_ai_security"
version = "0.1.0"
edition = "2021"

[dependencies]


near-sdk = { version = "5.0", features = ["legacy"] }
borsh = "1.5.4"
serde = { version = "1.0", features = ["derive"] }
